version: '3.8'

services:
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data

  cache:
    image: redis:7.2-alpine
    ports:
      - '6379:6379'
      
  example-frontend:
    build:
      context: ./example-frontend
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8080
    container_name: frontend-app
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    ports:
      - 5000:5000
  example-backend:
    build: ./example-backend
    container_name: backend-app
    depends_on:
      - db
      - cache
    environment:
      - PORT=8080
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=cache
      - POSTGRES_HOST=db 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - 8080:8080
volumes:
  database: