FROM node:16-slim

WORKDIR /usr/src/app

COPY . .

RUN npm install

# Set environment variable
ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN REACT_APP_BACKEND_URL=http://localhost:8080 npm run build

COPY build* ./

RUN npm install -g serve

EXPOSE 5000

CMD [ "serve", "-s", "-l", "5000", "build" ]